#!/bin/sh
LC_ALL=en_US.UTF-8
export LANG
LANGUAGE=en
export LANGUAGE

URL=https://l10n.gnome.org
BRANCH=
TARGET=po
MODULE=
ACTIVITY=

usage() {
  cmd=`basename $0`
  echo "Usage: $cmd [-b <branch>] [-m] <module>"
}

OPT=`getopt ab:dhmt: "$@"`
if [ $? -ne 0 ]; then
  usage >&2
  exit 1
fi
eval set -- "$OPT"
while :; do
  case "$1" in
  -a)
    ACTIVITY=true
    break
    ;;
  -b)
    BRANCH=$2
    shift 2
    ;;
  -d)
    # Now this is default funcion
    shift 1
    ;;
  -h)
    usage
    exit 0
    ;;
  -m)
    TARGET=help
    shift 1
    ;;
  -t)
    TARGET=$2
    shift 2
    ;;
  --)
    shift 1
    break;
    ;;
  *)
    usage >&2
    exit 1
    ;;
  esac
done

if [ x"$1" = x ]; then
  MODULE=`basename "$PWD"`
else
  MODULE="$1"
fi

if echo "$MODULE" |grep -q -- '-m$'; then
  MODULE=`echo "$MODULE" | sed -e 's/\(.*\)-m$/\1/'`
  TARGET=help
fi
if echo "$MODULE" |grep -q -- '-b-'; then
  BRANCH=`echo "$MODULE" | sed -e 's/^.*-b-\(.*\)$/\1/'`
  MODULE=`echo "$MODULE" | sed -e 's/^\(.*\)-b-.*$/\1/'`
fi


if [ x"$ACTIVITY" = x ]; then
  case "$MODULE" in
  gnome-help)
    MODULE=gnome-user-docs
    TARGET=gnome-help
    ;;
  getting-started|gnome-getting-started|gnome-getting-started-docs)
    MODULE=gnome-getting-started-docs
    TARGET=getting-started
    ;;
  gtk|gtk+|gtk-ui|gtk+-ui)
#     MODULE=Gtk-UI
    MODULE=gtk+
    ;;
  gtk-prop*|gtk+-prop*)
    MODULE=gtk+
    TARGET=po-properties
    ;;
  release-notes)
    TARGET=help
    ;;
  webkit)
    MODULE=webkit
    TARGET=webkit
    BRANCH=HEAD
  esac
  if [ x"$BRANCH" = x ]; then
    curbranch=`basename "\`git symbolic-ref HEAD 2>/dev/null\`"`
    if [ x"$curbranch" = x ]; then
      BRANCH=master
    else
      BRANCH="$curbranch"
    fi
  else
    BRANCH=`echo "$BRANCH" | sed -e 's/^\([0-9]\{1,\}\)[-.]\([0-9]\{1,\}\)$/gnome-\1-\2/'`
  fi
  URL="${URL}/vertimus/${MODULE}/${BRANCH}/${TARGET}/ja"
else
  URL="${URL}/vertimus/ja/activity_summary/"
fi

if [ x"$VIM" = x ]; then
  EDITOR='vim'
else
#   EDITOR="vim -c 'map! <C-t> <ESC>'"
  EDITOR="nano"
fi
export EDITOR

w3m -header 'Accept-Language:en_US' -no-mouse "$URL"
