#!/bin/sh

URL=http://l10n.gnome.org
BRANCH=
TARGET=po
MODULE=
ACTIVITY=

usage() {
  cmd=`basename $0`
  echo "Usage: $cmd [-b <branch>] [-m] <module>"
}

OPT=`getopt ab:dhm "$@"`
if [ $? -ne 0 ]; then
  usage >&2
  exit 1
fi
eval set -- "$OPT"
while :; do
  case "$1" in
  -a)
    ACTIVITY=true
    break
    ;;
  -b)
    BRANCH=`echo "$2" | sed -e 's/^\([0-9]\{1,\}\)[-.]\([0-9]\{1,\}\)$/gnome-\1-\2/'`
    shift 2
    ;;
  -d)
    MODULE=`basename "$PWD"`
    if echo $MODULE | grep -q -- '-m$'; then
      MODULE=`echo $MODULE | sed -e 's/\(.*\)-m$/\1/'`
      TARGET=help
    fi
    shift 1
    ;;
  -h)
    usage
    exit 0
    ;;
  -m)
    TARGET=help
    shift 1
    ;;
  --)
    shift 1
    break;
    ;;
  *)
    usage >&2
    exit 1
    ;;
  esac
done

if [ x"$ACTIVITY" != x ]; then
  URL="${URL}/vertimus/ja/activity_summary/"
else
  if [ x"$MODULE" = x ]; then
    MODULE="$1"
  fi
    case "$MODULE" in
    gnome-help)
      MODULE=gnome-user-docs
      TARGET=gnome-help
      ;;
    getting-started|gnome-getting-started-docs)
      MODULE=gnome-getting-started-docs
      TARGET=gnome-help
      ;;
    gtk|gtk+|gtk-ui|gtk+-ui)
      MODULE=Gtk-UI
      ;;
    gtk-prop*|gtk+-prop*)
      MODULE=Gtk-properties
      TARGET=po-properties
      ;;
    esac
  if [ x"$BRANCH" = x ]; then
    curbranch=`basename "\`git symbolic-ref HEAD 2>/dev/null\`"`
    if [ x"$curbranch" = x ]; then
      BRANCH=master
    else
      BRANCH="$curbranch"
    fi
  fi
  URL="${URL}/vertimus/${MODULE}/${BRANCH}/${TARGET}/ja"
fi

if [ x"$VIM" = x ]; then
  EDITOR='vim'
else
#   EDITOR="vim -c 'map! <C-t> <ESC>'"
  EDITOR="nano"
fi
export EDITOR
if lsb_release -d |grep Debian -q; then
  LANGUAGE=en
  export LANGUAGE
else
  LANG=en_US.UTF-8
  export LANG
fi

w3m -no-mouse "$URL"
